---
driver_plugin: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-12.04
  run_list:
  - recipe[apt]
- name: ubuntu-14.04
  run_list:
  - recipe[apt]
- name: centos-6.5
  run_list:
  - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[crowd]
      apt:
        compiletime: true
