---
driver_config:
  openstack_username: <%= ENV['OPENSTACK_USERNAME'] %>
  openstack_api_key: <%= ENV['OPENSTACK_API_KEY'] %>
  openstack_auth_url: <%= ENV['OPENSTACK_AUTH_URL'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: ubuntu-1404
  driver_plugin: openstack
  driver_config:
    image_ref: Ubuntu Server 14.04
    flavor_ref: mx.medium
    floating_ip_pool: nova
    key_name: <%= ENV['KEY_NAME'] %>
    private_key_path: <%= ENV['PRIVATE_KEY_PATH'] %>
    username: ubuntu
    server_name: crowd-dev
    disable_ssl_validation: true
    no_ssh_tcp_check: true
    no_ssh_tcp_check_sleep: 20

suites:
  - name: default
    run_list:
      - recipe[crowd]
