AllCops:
  Exclude:
    - vendor/**/*
Documentation:
  Enabled: false
AlignParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
#
# we like our neatly-aligned code too much
#
SingleSpaceBeforeFirstArg:
  Enabled: false

# TODO: move to compact style later?
ClassAndModuleChildren:
  Enabled: false

ShadowingOuterLocalVariable:
  Enabled: false

Style/FileName:
  Enabled: false
